Run MacOS software update tool at the end of the script!

diff --git a/Update b/Update
--- a/Update
+++ b/Update
@@ -1,33 +1,35 @@
-#!/bin/bash 
+#!/bin/bash
 
-# Update : 
+# Update :
 # Simple bash script to run mac system and terminal tools update.
-# Updated : May 2020
+# Updated : November 2020
 
 # set -x # Debug mode.
 # set -n # Run w/o execution.
 
 {
-trap 'echo "Nope!!!"' SIGINT SIGTERM SIGTSTP # Trap signal
+# Trap signal
+trap 'echo "Cannot stop now. Give it a minute!"' SIGINT SIGTERM SIGTSTP 
 
 printf "\nHello Dede.\n"
-
-# Mac Operating system update. 
-printf "\nStarting MacOS Update ...\n"
-printf "Please provide system "
-sudo softwareupdate -iaR
 
 # Mac App Store applications update.
 printf "\nStarting Mac Appstore Apps update ...\n"
 mas upgrade
 
-# Applications update via Brew. 
+# Applications update via Brew.
 printf "\nStarting Brew Cask Update ...\n"
-brew cask upgrade
+# brew cask upgrade # deprecated
+brew upgrade --cask
 
 # Brew packages update.
 printf "\nStartting Brew packages update and upgrade ...\n"
 brew upgrade && brew update
+
+# Mac Operating system update.
+printf "\nStarting MacOS Update ...\n"
+printf "Please provide system "
+sudo softwareupdate -iaR --verbose
 
 }
 exit 0
